name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  packages: write

jobs:
  unity:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IMAGE_OPT: oci-mediatypes=true,compression=zstd,compression-level=20,force-compression=true
      PROJECT: /MedicineCI
    strategy:
      fail-fast: false
      matrix:
        UNITY_VERSION: [
          # 2022.3
          2022.3.0f1,
          2022.3.1f1,
          2022.3.2f1,
          2022.3.3f1,
          2022.3.4f1,
          2022.3.5f1,
          2022.3.6f1,
          2022.3.7f1,
          2022.3.8f1,
          2022.3.9f1,
          2022.3.10f1,
          2022.3.11f1,
          2022.3.12f1,
          2022.3.13f1,
          2022.3.14f1,
          2022.3.15f1,
          2022.3.16f1,
          2022.3.17f1,
          2022.3.18f1,
          2022.3.19f1,
          2022.3.20f1,
          2022.3.21f1,
          2022.3.22f1,
          2022.3.23f1,
          2022.3.24f1,
          2022.3.25f1,
          2022.3.26f1,
          2022.3.27f1,
          2022.3.28f1,
          2022.3.29f1,
          2022.3.30f1,
          2022.3.31f1,
          2022.3.32f1,
          2022.3.33f1,
          2022.3.34f1,
          2022.3.35f1,
          2022.3.36f1,
          2022.3.37f1,
          2022.3.38f1,
          2022.3.39f1,
          2022.3.40f1,
          2022.3.41f1,
          2022.3.42f1,
          2022.3.43f1,
          2022.3.44f1,
          2022.3.45f1,
          2022.3.46f1,
          2022.3.47f1,
          2022.3.48f1,
          2022.3.49f1,
          2022.3.50f1,
          2022.3.51f1,
          2022.3.52f1,
          2022.3.53f1,
          2022.3.54f1,
          2022.3.55f1,
          2022.3.56f1,
          2022.3.57f1,
          2022.3.58f1,
          2022.3.59f1,
          2022.3.60f1,
          2022.3.61f1,
          2022.3.62f1,
          # 2023.2
          2023.2.0f1,
          2023.2.1f1,
          2023.2.2f1,
          2023.2.3f1,
          2023.2.4f1,
          2023.2.5f1,
          2023.2.6f1,
          2023.2.7f1,
          2023.2.8f1,
          2023.2.9f1,
          2023.2.10f1,
          2023.2.11f1,
          2023.2.12f1,
          2023.2.13f1,
          2023.2.14f1,
          2023.2.15f1,
          2023.2.16f1,
          2023.2.17f1,
          2023.2.18f1,
          2023.2.19f1,
          2023.2.20f1,
          # 2023.3
          2023.3.0b10,
          # 6.0
          6000.0.0f1,
          6000.0.1f1,
          6000.0.2f1,
          6000.0.3f1,
          6000.0.4f1,
          6000.0.5f1,
          6000.0.6f1,
          6000.0.7f1,
          6000.0.8f1,
          6000.0.9f1,
          6000.0.10f1,
          6000.0.11f1,
          6000.0.12f1,
          6000.0.13f1,
          6000.0.14f1,
          6000.0.15f1,
          6000.0.16f1,
          6000.0.17f1,
          6000.0.18f1,
          6000.0.19f1,
          6000.0.20f1,
          6000.0.21f1,
          6000.0.22f1,
          6000.0.23f1,
          6000.0.24f1,
          6000.0.25f1,
          6000.0.26f1,
          6000.0.27f1,
          6000.0.28f1,
          6000.0.29f1,
          6000.0.30f1,
          6000.0.31f1,
          6000.0.32f1,
          6000.0.33f1,
          6000.0.34f1,
          6000.0.35f1,
          6000.0.36f1,
          6000.0.37f1,
          6000.0.38f1,
          6000.0.39f1,
          6000.0.40f1,
          6000.0.41f1,
          6000.0.42f1,
          6000.0.43f1,
          6000.0.44f1,
          6000.0.45f1,
          6000.0.46f1,
          6000.0.47f1,
          6000.0.48f1,
          6000.0.49f1,
          6000.0.50f1,
          6000.0.51f1,
          6000.0.52f1,
          6000.0.53f1,
          6000.0.54f1,
          6000.0.55f1,
          # 6.1
          6000.1.0f1,
          6000.1.1f1,
          6000.1.2f1,
          6000.1.3f1,
          6000.1.4f1,
          6000.1.5f1,
          6000.1.6f1,
          6000.1.7f1,
          6000.1.8f1,
          6000.1.9f1,
          6000.1.10f1,
          6000.1.11f1,
          6000.1.12f1,
          6000.1.13f1,
          6000.1.14f1,
          6000.1.15f1,
          6000.1.16f1,
          # 6.2
          6000.2.0f1,
          # 6.3
          6000.3.0a3,
        ]

    #        UNITY_VERSION: [
#          # 2022.3
#          2022.3.0f1, 2022.3.62f1,
#          # 2023.2
#          2023.2.0f1, 2023.2.20f1,
#          # 2023.3
#          2023.3.0b10,
#          # 6.0
#          6000.0.0f1, 6000.0.55f1,
#          # 6.1
#          6000.1.0f1, 6000.1.16f1,
#          # 6.2
#          6000.2.0f1,
#          # 6.3
#          6000.3.0a3,
#        ]

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prep vars
        run: |
          REPO='${{ github.repository }}'
          REPO_LC=$(echo "$REPO" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LC=$REPO_LC" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=ghcr.io/$REPO_LC/unity-ci:${{ github.sha }}-${{ matrix.UNITY_VERSION }}" >> "$GITHUB_ENV"
          echo "CACHE_REF=ghcr.io/$REPO_LC/unity-ci:cache-${{ matrix.UNITY_VERSION }}" >> "$GITHUB_ENV"

      - uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          file: ./.github/workflows/Dockerfile
          push: false
          tags: ${{ env.IMAGE_TAG }}
          build-args: |
            UNITY_VERSION=${{ matrix.UNITY_VERSION }}
            PROJECT=${{ env.PROJECT }}
          secrets: |
            unity_serial=${{ secrets.UNITY_SERIAL }}
            unity_user=${{ secrets.UNITY_USER }}
            unity_password=${{ secrets.UNITY_PASSWORD }}
          outputs: |
            type=docker
          cache-from: type=registry,ref=${{ env.CACHE_REF }}
          cache-to: type=registry,ref=${{ env.CACHE_REF }},mode=min

      - name: Prepare secrets and license dir
        run: |
          echo "::add-mask::${{ secrets.UNITY_SERIAL }}"
          echo "::add-mask::${{ secrets.UNITY_USER }}"
          masked="${{ secrets.UNITY_SERIAL }}"
          masked="${masked%????}XXXX"
          echo "::add-mask::$masked"
          echo "LIC_DIR=$RUNNER_TEMP/unity-lic" >> "$GITHUB_ENV"
          mkdir -p "$RUNNER_TEMP/unity-lic"
          mkdir -p "$RUNNER_TEMP/unity-secrets"
          install -m 600 /dev/null "$RUNNER_TEMP/unity-secrets/unity_serial"
          install -m 600 /dev/null "$RUNNER_TEMP/unity-secrets/unity_user"
          install -m 600 /dev/null "$RUNNER_TEMP/unity-secrets/unity_password"
          printf '%s' '${{ secrets.UNITY_SERIAL }}' > "$RUNNER_TEMP/unity-secrets/unity_serial"
          printf '%s' '${{ secrets.UNITY_USER }}' > "$RUNNER_TEMP/unity-secrets/unity_user"
          printf '%s' '${{ secrets.UNITY_PASSWORD }}' > "$RUNNER_TEMP/unity-secrets/unity_password"

      - name: Run tests
        run: |
          size_bytes=$(docker image inspect "${{ env.IMAGE_TAG }}" --format='{{.Size}}')
          size_mib=$(awk -v b="$size_bytes" 'BEGIN{printf "%.2f", b/1024/1024}')
          echo "Docker image size: ${size_mib} MiB"
          docker run --rm \
            -v "$GITHUB_WORKSPACE:$PROJECT/Packages/Medicine/" \
            -v "$RUNNER_TEMP/test-results:$PROJECT/test-results" \
            -v "$LIC_DIR:/root/.local/share/unity3d" \
            -v "$RUNNER_TEMP/unity-secrets:/run/secrets:ro" \
            -w $PROJECT \
            "${{ env.IMAGE_TAG }}" \
            unity-editor \
              -projectPath $PROJECT \
              -executeMethod CI.RunTests

      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Unity Test Results
          reporter: dotnet-nunit
          path: "${{ runner.temp }}/test-results/*tests.xml"
          fail-on-error: false